
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://114.215.198.238:4502/oomall_other?serverTimezone=GMT%2B8
    username: root
    password: 123456789
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

  redis:
    # Redis服务器地址
    host: 114.215.198.238
    # Redis服务器连接端口
    port: 4506
    # Redis服务器连接密码
    password: 123456